// For Logic
export const ProControllerConfig: { [key: string]: number } = {
  A: 0,
  B: 1,
  X: 2,
  Y: 3,
  LB: 4,
  RB: 5,
  LT: 6,
  RT: 7,
  Back: 8,
  Start: 9,
  LS: 10,
  RS: 11,
  DPadUp: 12,
  DPadDown: 13,
  DPadLeft: 14,
  DPadRight: 15,
  LeftStickX: 18,
  LeftStickY: 19,
  RightStickX: 20,
  RightStickY: 21,
};

// For Display
export const ProControllerButtonNames: { [key: number]: string } = {
  0: "B",
  1: "A",
  2: "Y",
  3: "X",
  4: "L",
  5: "R",
  6: "ZL",
  7: "ZR",
  8: "-",
  9: "+",
  10: "L-Stick",
  11: "R-Stick",
  12: "↑",
  13: "↓",
  14: "←",
  15: "→",
  16: "HOME",
  17: "CAPTURE",
  18: "L-Stick (X)",
  19: "L-Stick (Y)",
  20: "R-Stick (X)",
  21: "R-Stick (Y)",
  99: "Void",
};

// For Arduino
export const SwitchControlLibrary: { [key: number]: string } = {
  0: "B",
  1: "A",
  2: "Y",
  3: "X",
  4: "L",
  5: "R",
  6: "ZL",
  7: "ZR",
  8: "MINUS",
  9: "PLUS",
  10: "LCLICK",
  11: "RCLICK",
  12: "UP",
  13: "DOWN",
  14: "LEFT",
  15: "RIGHT",
  16: "HOME",
  17: "CAPTURE",
  18: "L-Stick (X)",
  19: "L-Stick (Y)",
  20: "R-Stick (X)",
  21: "R-Stick (Y)",
  99: "Void",
};
